apiVersion: v1
kind: Pod
metadata:
 name: petclinicpod
 labels:
   app: web
spec:
 containers:
   - name: db
     image: mysql
     env:
       - name: MYSQL_ROOT_PASSWORD
         value: "petclinic"
       - name: MYSQL_DATABASE
         value: "petclinic"
   - name: petclinic
     image: anthonydahanne/spring-petclinic
     ports:
       - containerPort: 8080 #which port the container exposes
